version: "3"
services: 
    web:
        build: .
        ports: 
            - "80:80"
        restart: always
        env_file: 
            - .env
        volumes: 
            - .:/myportfolio
    
    db:
        image: postgres
        restart: always
        env_file: 
            - .env
